version: '3.4'

services:
  java:
    build:
      context: ../
    container_name: fieldapi
    hostname: fieldapi
    ports:
      - 8080:8080
    depends_on:
      - mongo
    networks:
      - "fieldapi-service"

  mongo:
    image: mongo:4.0.21
    container_name: mongo-field
    hostname: mongo-field
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    networks:
      - "fieldapi-service"

networks:
  fieldapi-service:
    driver: bridge

